### ISSUE TITLE
Missing CSS?

### ISSUE THREAD

**Issue by SiasMey** [karclouds/angular5-toaster#1]
Hi, you seem to have missing including the CSS file you mention in the demo and quick start section in your package.

**Comment by karclouds** [comment]
Hi, It's there under /src folder.  You will get the file under /node_modules/angular5-toaster/toaster.css when you install this package via npm.   'npm install angular5-toaster'.  Try and let me know if any issues with it. Thanks.

**Comment by SiasMey** [comment]
Aaah, dont know how I missed it. 

However, its not installed to the indicated path, /node_modules/angular5-toaster/toaster.css, its at /node_modules/angular5-toaster/src/toaster.css.
